
export default [
  { word: "rumor", hint: "Spread through whispers" },
  { word: "happen", hint: "Occur or take place" },
  { word: "match", hint: "Contest between two teams" },
  { word: "sail", hint: "Move a boat using wind power" },
  { word: "sick", hint: "Feeling unwell" },
  { word: "floor", hint: "Ground level in a building" },
  { word: "summit", hint: "Highest point or peak" },
  { word: "shadow", hint: "Dark area created by blocking light" },
  { word: "census", hint: "Population count" },
  { word: "chorus", hint: "Group singing in harmony" },
  { word: "launch", hint: "Start or set in motion" },
  { word: "abbey", hint: "Monastery or convent" },
  { word: "eject", hint: "Forcefully expel or throw out" },
  { word: "resist", hint: "Oppose or withstand" },
  { word: "guilt", hint: "Feeling of responsibility for a wrongdoing" },
  { word: "repeat", hint: "Do again or replicate" },
  { word: "drama", hint: "Theatrical performance or intense event" },
  { word: "easy", hint: "Simple or not difficult" },
  { word: "morsel", hint: "Small piece of food" },
  { word: "swipe", hint: "Quick movement with the hand" },
  { word: "equip", hint: "Provide with necessary tools or equipment" },
  { word: "reader", hint: "Person who reads" },
  { word: "pray", hint: "Communicate with a higher power" },
  { word: "grave", hint: "Burial place or serious in nature" },
  { word: "cord", hint: "Thick string or rope" },
  { word: "cheek", hint: "Side of the face" },
  { word: "figure", hint: "Shape or numerical symbol" },
  { word: "rebel", hint: "Resist authority or control" },
  { word: "native", hint: "Indigenous or originating in a particular place" },
  { word: "rack", hint: "Framework for holding or storing items" },
  { word: "fade", hint: "Gradually disappear or lose color" },
  { word: "basket", hint: "Container for holding items" },
  { word: "reform", hint: "Make changes for improvement" },
  { word: "hall", hint: "Large room or passageway" },
  { word: "area", hint: "Region or space" },
  { word: "root", hint: "Underground part of a plant" },
  { word: "breeze", hint: "Gentle wind" },
  { word: "shift", hint: "Change in position or direction" },
  { word: "cane", hint: "Walking stick or slender, flexible stick" },
  { word: "cash", hint: "Money in the form of coins or banknotes" }
];
